spring:
  datasource:
    username: root
    password: Mysql@1234
    url: jdbc:mysql://localhost:3306/ComplaintForms
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true